### ISSUE TITLE
Demo project fails to load on linux

### ISSUE THREAD

**Issue by MaximLippeveld** [unipept/unipept-desktop#135]
Tested on latest Fedora with the AppImage.

To reproduce:
1. Open the AppImage
2. Click "Open demo project"

Loading fails with following error in the console
`Error: ENOENT: no such file or directory, lstat '/tmpDemo project/'`

**Comment by pverscha** [comment]
Dear @MaximLippeveld,

Thank you for your bug report. I was able to reproduce this issue on Ubuntu, so it probably occurs on all Linux-based operating systems. It seems like a path separator is missing between "tmp" and "Demo project". I will try to fix this as soon as possible.

**Comment by pverscha** [comment]
This issue has been fixed and a new version of the application has been released that incorporates this fix (v1.2.0).
