### ISSUE TITLE
Implement autoupdater

### ISSUE THREAD

**Issue by pverscha** [unipept/unipept-desktop#28]
The first release of the Unipept Desktop application should include an auto-updater, which automatically downloads and installs a new version of this application once it's available.

**Comment by pverscha** [comment]
Auto updating is done, however there are some things we should take into account for the future:

A bug in `electron-updater` that's present since version 4.2.3 and upwards, causes downloads of files to fail after 30 seconds. I've fixed the electron-updater package version to 4.2.2 at this point. If the issues described [here](https://github.com/electron-userland/electron-builder/issues/4744) and [here](https://github.com/electron-userland/electron-builder/pull/4649) are fixed, we can safely upgrade to the new version again.

**Comment by lidel** [comment]
@pverscha do you know if the bug is platform agnostic, or limited to macOS?

**Comment by pverscha** [comment]
@lidel This bug is platform agnostic afaik. Please note that this is an issue for ‘unipept-desktop’, an app that uses electron-updater. I refer you to the official electron-updater repo for support on that issue.
